### ISSUE TITLE
java.lang.NullPointerException: Cannot invoke "net.minecraftforge.common.util.ForgeDirection.ordinal()" because "this.EtchedNagastoneNorth" is null

### ISSUE THREAD

**Issue by AsimutMLS** [GTNewHorizons/twilightforest#90] opened 2024-09-22 08:23 UTC
NAGA boss structure crashes.

java.lang.NullPointerException: Cannot invoke "net.minecraftforge.common.util.ForgeDirection.ordinal()" because "this.EtchedNagastoneNorth" is null
at RFB-Launch//twilightforest.structures.courtyard.ComponentTFNagaCourtyardWall.func_74875_a(ComponentTFNagaCourtyardWall.java:576)
at RFB-Launch//net.minecraft.world.gen.structure.StructureStart.func_75068_a(StructureStart.java:44)
at RFB-Launch//net.minecraft.world.gen.structure.MapGenStructure.func_75051_a(MapGenStructure.java:93)
at RFB-Launch//twilightforest.world.ChunkProviderTwilightForest.func_73153_a(ChunkProviderTwilightForest.java:950)
at RFB-Launch//net.minecraft.world.gen.ChunkProviderServer.func_73153_a(ChunkProviderServer.java:279)
at RFB-Launch//net.minecraft.world.chunk.Chunk.func_76624_a(Chunk.java:1040)
at RFB-Launch//net.minecraft.world.gen.ChunkProviderServer.originalLoadChunk(ChunkProviderServer.java:190)
at RFB-Launch//net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:131)
at RFB-Launch//net.minecraft.world.gen.ChunkProviderServer.func_73158_c(ChunkProviderServer.java:101)
at RFB-Launch//net.minecraft.world.gen.ChunkProviderServer.func_73154_d(ChunkProviderServer.java:199)
at RFB-Launch//net.minecraft.world.World.func_72964_e(World.java:419)
at RFB-Launch//net.minecraft.world.WorldServer.func_147456_g(WorldServer.java:313)
at RFB-Launch//net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:183)
at RFB-Launch//net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:625)
at RFB-Launch//net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334)
at RFB-Launch//net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
at RFB-Launch//net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
at RFB-Launch//net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
at RFB-Launch//twilightforest.structures.courtyard.ComponentTFNagaCourtyardWall.func_74875_a(ComponentTFNagaCourtyardWall.java:576)
at RFB-Launch//net.minecraft.world.gen.structure.StructureStart.func_75068_a(StructureStart.java:44)
at RFB-Launch//net.minecraft.world.gen.structure.MapGenStructure.func_75051_a(MapGenStructure.java:93)
at RFB-Launch//twilightforest.world.ChunkProviderTwilightForest.func_73153_a(ChunkProviderTwilightForest.java:950)
at RFB-Launch//net.minecraft.world.gen.ChunkProviderServer.func_73153_a(ChunkProviderServer.java:279)
at RFB-Launch//net.minecraft.world.chunk.Chunk.func_76624_a(Chunk.java:1040)
at RFB-Launch//net.minecraft.world.gen.ChunkProviderServer.originalLoadChunk(ChunkProviderServer.java:190)
at RFB-Launch//net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:131)
at RFB-Launch//net.minecraft.world.gen.ChunkProviderServer.func_73158_c(ChunkProviderServer.java:101)
at RFB-Launch//net.minecraft.world.gen.ChunkProviderServer.func_73154_d(ChunkProviderServer.java:199)
at RFB-Launch//net.minecraft.world.World.func_72964_e(World.java:419)
at RFB-Launch//net.minecraft.world.WorldServer.func_147456_g(WorldServer.java:313)
at RFB-Launch//net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:183)

**Comment by Lyfts** [comment] 2024-09-22 08:25
Duplicate of https://github.com/GTNewHorizons/twilightforest/issues/83

**Closed by Lyfts** 2024-09-22 08:25 UTC

**Comment by AsimutMLS** [comment] 2024-09-22 08:27
> Duplicate of #83

sorry. my fail.

**Comment by AsimutMLS** [comment] 2024-09-22 08:31
I'll check out the fix now
