### ISSUE TITLE
NullPointerException Crash

### ISSUE THREAD

**Issue by enimog** [GTNewHorizons/twilightforest#80] opened 2024-07-04 22:36 UTC
Hello, I had this crash on my server today (Version 2.6.1):

```
Description: Exception in server tick loop

java.lang.NullPointerException: Cannot invoke "net.minecraftforge.common.util.ForgeDirection.ordinal()" because "this.EtchedNagastoneNorth" is null
	at RFB-Launch//twilightforest.structures.courtyard.ComponentTFNagaCourtyardWall.func_74875_a(ComponentTFNagaCourtyardWall.java:576)
	at RFB-Launch//net.minecraft.world.gen.structure.StructureStart.func_75068_a(StructureStart.java:44)
	at RFB-Launch//net.minecraft.world.gen.structure.MapGenStructure.func_75051_a(MapGenStructure.java:93)
	at RFB-Launch//twilightforest.world.ChunkProviderTwilightForest.func_73153_a(ChunkProviderTwilightForest.java:950)
	at RFB-Launch//net.minecraft.world.gen.ChunkProviderServer.func_73153_a(ChunkProviderServer.java:279)
	at RFB-Launch//net.minecraft.world.chunk.Chunk.func_76624_a(Chunk.java:1040)
	at RFB-Launch//net.minecraftforge.common.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:52)
	at RFB-Launch//net.minecraftforge.common.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:12)
	at RFB-Launch//net.minecraftforge.common.util.AsynchronousExecutor$Task.finish(AsynchronousExecutor.java:189)
	at RFB-Launch//net.minecraftforge.common.util.AsynchronousExecutor.finishActive(AsynchronousExecutor.java:354)
	at RFB-Launch//net.minecraftforge.common.chunkio.ChunkIOExecutor.tick(ChunkIOExecutor.java:30)
	at RFB-Launch//net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:596)
	at RFB-Launch//net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334)
	at RFB-Launch//net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at RFB-Launch//net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at RFB-Launch//net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
```

**Comment by chochem** [comment] 2024-07-04 22:38
Duplicate of https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/16353 and 20 others.

You can update twilight forest to https://github.com/GTNewHorizons/twilightforest/releases/tag/2.6.12

**Closed by chochem** 2024-07-04 22:38 UTC
